// One-off generation script — NOT part of the runtime app bundle.
// Converts world-atlas topojson into:
//   1. an SVG <path> string for the world map outline
//   2. a lookup of country name -> projected [x, y] centroid (for plotting status pins)
//
// Run with: node scripts/generate-map.mjs
// Output:   src/data/worldMap.generated.ts
//
// Re-run only if you want to change the map projection/size — the output is
// committed to the repo so the app never needs these geo libraries at runtime.

import { geoPath, geoNaturalEarth1, geoCentroid } from 'd3-geo';
import { feature } from 'topojson-client';
import countries110m from 'world-atlas/countries-110m.json' with { type: 'json' };
import fs from 'node:fs';

const WIDTH = 960;
const HEIGHT = 500;

const projection = geoNaturalEarth1().fitSize([WIDTH, HEIGHT], { type: 'Sphere' });
const path = geoPath(projection);

const geo = feature(countries110m, countries110m.objects.countries);

const pathD = path(geo);

const centroids = {};
for (const f of geo.features) {
  const name = f.properties?.name;
  if (!name) continue;
  const c = projection(geoCentroid(f));
  if (c) centroids[name] = [Math.round(c[0] * 10) / 10, Math.round(c[1] * 10) / 10];
}

const output = `// AUTO-GENERATED by scripts/generate-map.mjs — do not hand-edit.
// Natural Earth 1 projection, fitted to a ${WIDTH}x${HEIGHT} viewBox.

export const WORLD_MAP_VIEWBOX = '0 0 ${WIDTH} ${HEIGHT}';

export const WORLD_MAP_PATH = ${JSON.stringify(pathD)};

export const COUNTRY_CENTROIDS: Record<string, [number, number]> = ${JSON.stringify(centroids, null, 2)};
`;

fs.mkdirSync('src/data', { recursive: true });
fs.writeFileSync('src/data/worldMap.generated.ts', output);

console.log(`Wrote src/data/worldMap.generated.ts — ${Object.keys(centroids).length} country centroids.`);
